import React from 'react';
import Head from 'next/head';
import { Inter } from 'next/font/google';
import NavBar from '../components/NavBar';

const inter = Inter({ subsets: ['latin'] });

const Home = () => {
  return (
    <>
      
        <title>MyQbix - Your Favourite Stream Drama</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
      <NavBar />
      <div className="text-black text-center mt-8">
        <h1 className="text-4xl font-bold">Welcome to MyQbix</h1>
        <p className="mt-4">Stream your favorite dramas</p>
      </div>
    </>
  );
};

export default Home;